### ISSUE TITLE
Small bug in colab notebook

### ISSUE THREAD

**Issue by Br1lopez** [JingyunLiang/SwinIR#101]
Hi there!

I was using the colab notebook [**SwinIR demo on Real-World Image SR.ipynb** ](https://colab.research.google.com/gist/JingyunLiang/a5e3e54bc9ef8d7bf594f6fee8208533/swinir-demo-on-real-world-image-sr.ipynb) and the ESRGAN output was not woking.

I changed the ESRGAN lines in inference to 

```
# realESRGAN
if test_patch_wise:
  !python inference_realesrgan.py -n RealESRGAN_x4plus --input BSRGAN/testsets/RealSRSet -s 4 --output results/realESRGAN --tile 800
else:
  !python inference_realesrgan.py -n RealESRGAN_x4plus --input BSRGAN/testsets/RealSRSet -s 4 --output results/realESRGAN
```

...and now it works.

I'm posting this in case this is a generalized problem for anyone else.

Thanks!

**Comment by JingyunLiang** [comment]
Thank you very much. I have corrected it.
