### ISSUE TITLE
question about half precision for test.

### ISSUE THREAD

**Issue by arnaud-nt2i** [JingyunLiang/SwinIR#103]
Hi, @JingyunLiang @chenxwh thank you for your great work on this repo (and others).
I'm trying to speed up a bit SwinIr tests (real sr) by running it in fp16 precision.
I set ` model = model.half()` after  ` model = model.to(device)` in main_test_swinir.py : https://github.com/JingyunLiang/SwinIR/blob/9b1a9bf5d1df3b18c32a49ea82f60c313d779f7d/main_test_swinir.py#L46
`img_lq = img_lq.half()` after https://github.com/JingyunLiang/SwinIR/blob/9b1a9bf5d1df3b18c32a49ea82f60c313d779f7d/main_test_swinir.py#L63
and ` x = (attn.half() @ v).transpose(1, 2).reshape(B_, N, C)` instead of  https://github.com/JingyunLiang/SwinIR/blob/9b1a9bf5d1df3b18c32a49ea82f60c313d779f7d/models/network_swinir.py#L142

but I got no significant speed up and worst, the resulting images are black with some artifacs...
My question is can we speed up swinir by setting fp16, half precision ? and if yes, how ?

**Comment by JingyunLiang** [comment]
I think you'd better use mixed_precision to do it, as float32 cannot be transformed to float16 loselessly. Another option is to use torch.bfloat16 (You need newest GPUs).

**Comment by tornikeo** [comment]
This is an interesting issue. I just found out that the reason behind fp16 instability is that x (shown below) is getting out of the range of fp16 during inference. Try to debug this piece of code - in main `class SwinIR`. If you look at `x.std()` during the iteration throughout `self.layers`, you will find that `std` is increasing exponentially. After 6 iterations, it is beyond the range of fp16 and gets converted into NANs. This is then clipped to be 1.0 at the end, and hence your black screen. @JingyunLiang , should this be the case here? I see that even when using fp32, the `x.std()` is increasing exponentially during looping. 

```python
    def forward_features(self, x):
        x_size = (x.shape[2], x.shape[3])
        x = self.patch_embed(x)
        if self.ape:
            x = x + self.absolute_pos_embed
        x = self.pos_drop(x)

        for layer in self.layers:
            x = layer(x, x_size) # Here! It explodes on fp16 after reaching `x.std() > 52000`

        x = self.norm(x)  # B L C
        x = self.patch_unembed(x, x_size)

        return x
```
