### ISSUE TITLE
request pretrained discriminator

### ISSUE THREAD

**Issue by LuoXin-s** [JingyunLiang/SwinIR#104]
Request pretrained discriminator corresponding to [003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth](https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth)

**Comment by JingyunLiang** [comment]
Sorry that the D has been cleaned. You can follow the training code to train it. It's relatively stable.
