### ISSUE TITLE
swin layer

### ISSUE THREAD

**Issue by jiaaihhy** [JingyunLiang/SwinIR#13]
In swin transformer, self attention module conclude two subnet, one is simple windows self attention, another is shifted windows.in that code, in normal first windows self attention, there is no attn_mask, second shifted windows have mask. but in your code, seemly every self-attention layers have the attn_mask. that means every swin layer dont have windows self-attn, instead by all shifted windows in every layer? thank you

**Comment by JingyunLiang** [comment]
For non-shift layers, we set `attn_mask=None`. See https://github.com/JingyunLiang/SwinIR/blob/5bd10ce32d6fd39b74f44a9b46b3a4da063dd946/models/network_swinir.py#L211

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
