### ISSUE TITLE
FLOPs?

### ISSUE THREAD

**Issue by vztu** [JingyunLiang/SwinIR#18]
Hi,

Thanks for this great work! Could you provide the FLOPs/MACs of your SwinIR model?

**Comment by JingyunLiang** [comment]
We have already provided the FLOPs in [README.md](https://github.com/JingyunLiang/SwinIR/blob/main/README.md).

FYI

| Method             | Training Set    |  Training time  <br /> (8 GeForceRTX2080Ti <br /> batch=32, iter=500k) |Y-PSNR/Y-SSIM <br /> on Manga109 | Run time  <br /> (1 GeForceRTX2080Ti <br />, on 256x256 LR image)* |  #Params   | #FLOPs |  Testing memory |
| :---      | :---:        |        :-----:         |     :---:      |     :---:      |     :---:      |   :---:      |  :---:      |
| RCAN | DIV2K | 1.6 days | 31.22/0.9173 | 0.180s | 15.6M | 850.6G | 593.1M | 
| SwinIR | DIV2K | 1.8 days |31.67/0.9226 | 0.539s | 11.9M | 788.6G | 986.8M |

**Comment by wanglixilinx** [comment]
Hi, @JingyunLiang ,
  The FLops in the above table are calculated with the input resolution=256x256?

**Comment by JingyunLiang** [comment]
Runtime, #FLOPs and testing memory are all calculated on 256x256 LR image for X4 SR.

**Comment by vztu** [comment]
Hi, @JingyunLiang, how about the FLOPs for the denoising model on 256x256 inputs?

**Comment by JingyunLiang** [comment]
It is similar to the SR model because the main difference is the upsample module. The exact FLOPS for denoising on 256x256 models is  787.993G.

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
