### ISSUE TITLE
Problem about testing my trained model

### ISSUE THREAD

**Issue by hcleung3325** [JingyunLiang/SwinIR#20]
Thanks for the training code.
I train a classic model.
I get 500000_optimizerG.pth 500000_G.pth 500000_E.pth.
May I know which pth I should run during testing?
When I run 
`python main_test_swinir.py --task classical_sr --scale 4 --training_patch_size 64 --model_path superresolution/swinir_sr_classical_patch64_x4_l1/models/500000_G.pth --folder_lq testsets/real3wx4/test_LR_crop `
It seems cannot load the model 
model.load_state_dict(torch.load(args.model_path)['params'], strict=True)
KeyError: 'params'
May I know how to solve this?
Thanks.

**Comment by JingyunLiang** [comment]
Hi, sorry for this bug. Please remove `['params']` in Line 126
https://github.com/JingyunLiang/SwinIR/blob/96a446fd6ce6867f9660209e263a66af01d36e62/main_test_swinir.py#L126
as 
```
model.load_state_dict(torch.load(args.model_path), strict=True). 
```

**Comment by hcleung3325** [comment]
> Hi, sorry for this bug. Please remove `['params']` in Line 126
> https://github.com/JingyunLiang/SwinIR/blob/96a446fd6ce6867f9660209e263a66af01d36e62/main_test_swinir.py#L126
> 
> 
> as
> ```
> model.load_state_dict(torch.load(args.model_path), strict=True). 
> ```

Thanks for reply.
I notice that when I ran your pretrained model, the main_test_swinir.py works fine.
However, when I ran main_test_swinir.py with either 500000_optimizerG.pth 500000_G.pth 500000_E.pth, it occurs the above error.
Is it the 500000_G.pth has some problem?

**Comment by JingyunLiang** [comment]
The main difference between my pretrained model and yours (trained on KAIR) is that:
1, my pretrained model is a dict: `{'params': model}`.
2, KAIR's model is just the `model`.

Therefore, you have to use the following line to load my pretrained model:
```
model.load_state_dict(torch.load(args.model_path)['params'], strict=True) # specify the dict key
```
and the following line to load your trained model (on KAIR)
```
model.load_state_dict(torch.load(args.model_path), strict=True) # directly load it
```
Sorry for the inconsistence between KAIR and SwinIR testing code. We will fix this problem.

**Comment by JingyunLiang** [comment]
**Update: I have fixed the bug.**

**Comment by hcleung3325** [comment]
Thanks a lot.
