### ISSUE TITLE
about charbonnierloss

### ISSUE THREAD

**Issue by jiaaihhy** [JingyunLiang/SwinIR#22]
charbonnierloos have a extra parameter eps, in paper, eps is 1e-3, its true use is (1e-3) ^ 2, but in your code May be you dont take ^2 operations.  I Dont know its inference is important?

**Comment by JingyunLiang** [comment]
This is a minor mistake. `eps^2=1e-3` and `eps^2=1e-9` lead to the same results in my experiments. If you have to choose, I suggest you use `eps^2=1e-9` (a common practice).

**Comment by jiaaihhy** [comment]
thankyou

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
