### ISSUE TITLE
Can gan be finetuned on own dataset?

### ISSUE THREAD

**Issue by betterftr** [JingyunLiang/SwinIR#24]
When I try to set pretrained models (003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth) paths in KAIR's train file;

  , "path": {
    "root": "superresolution"  // "denoising" | "superresolution" | "dejpeg"
    , "pretrained_netG": null  // path of pretrained model
    , "pretrained_netD": null  // path of pretrained model
	, "pretrained_netE": null  // path of pretrained model
	}

it starts to train from scratch anyway. And when I copy  from model_zoo right into /superresolution/swinir_sr_realworld_x4_gan/models/ thats not working either.

**Comment by JingyunLiang** [comment]
Thanks for your question. We will fix it later.

**Comment by cszn** [comment]
You should change the file name `003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth` into `5000_G.pth`

**Comment by betterftr** [comment]
Yes, i tried it gives a long error ending with : Unexpected key(s) in state_dict: "params_ema".

**Comment by JingyunLiang** [comment]
Ref to  https://github.com/JingyunLiang/SwinIR/issues/20#issuecomment-920703374

We will try to fix this inconsistency later.

**Comment by betterftr** [comment]
Okay, can you tell me what line to change? The referred solution is for main_test_swinir.py not for training code from KAIR

**Comment by JingyunLiang** [comment]
Change
```
network.load_state_dict(torch.load(load_path), strict=strict)
```
to
```
network.load_state_dict(torch.load(load_path)['params_ema'], strict=strict)
```
at https://github.com/cszn/KAIR/blob/7d70f91bb7c03d8795a6bed29ee17b1c6b834e4e/models/model_base.py#L160.

Note: this is just a temporary solution (may result in problems for other experiments). We will solve this problem with a better solution later.
