### ISSUE TITLE
It sounds unfair to use different Training set like EDSR or ther methods.

### ISSUE THREAD

**Issue by fsword73** [JingyunLiang/SwinIR#25]
Need apple to apple training set to show the much better method or not better method .

**Comment by JingyunLiang** [comment]
Please see Table 2 for detailed results. **We provide two settings for comparison**. Setting 1 is identical to EDSR (a common setting for research paper), while Setting 2 is the same as RRDB (a common setting for SR challenges).

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
