### ISSUE TITLE
Trained model from KAIR (40000_optimizerG.pth) gives error on testing

### ISSUE THREAD

**Issue by paragon1234** [JingyunLiang/SwinIR#28]
Instead of using pre-trained models, I trained the KAIR code and used the generated model for testing.
```
The KAIR training code produced 3 models:
40000_optimizerG.pth
40000_G.pth
40000_E.pth
```

Using these models, for testing the code in this repository, I am getting error:

```
(pytorch-gpu) C:\Users\Downloads\SwinIR-main>python main_test_swinir.py --task classical_sr --scale 2 --training_patch_size 48 --folder_lq testsets/Set5/LR_bicubic/X2 --folder_gt testsets/Set5/HR
loading model from model_zoo/swinir/40000_optimizerG.pth
Traceback (most recent call last):
  File "C:\Users\Downloads\SwinIR-main\main_test_swinir.py", line 253, in <module>
    main()
  File "C:\Users\Downloads\SwinIR-main\main_test_swinir.py", line 42, in main
    model = define_model(args)
  File "C:\Users\Downloads\SwinIR-main\main_test_swinir.py", line 174, in define_model
    model.load_state_dict(pretrained_model[param_key_g] if param_key_g in pretrained_model.keys() else pretrained_model, strict=True)
  File "C:\Users\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SwinIR:
        Missing key(s) in state_dict: "conv_first.weight", "conv_first.bias", "patch_embed.norm.weight", "patch_embed.norm.bias", "layers.0.residual_group.blocks.0.norm1.weight", "layers.0.residual_group.blocks.0.norm1.bias", "layers.0.residual_group.blocks.0.attn.relative_position_bias_table",
```

40000_G.pth
40000_E.pth
are testing fine

**Comment by JingyunLiang** [comment]
Do you use the latest code? We have fixed the bug as follows:
https://github.com/cszn/KAIR/blob/60ddfc0ffb320182c82f7c93f741615dd6a7033b/main_test_swinir.py#L176

See more discussions here https://github.com/JingyunLiang/SwinIR/issues/20

**Comment by paragon1234** [comment]
Yes I am using latest code for SwinIR/main_test_swinir.py. It worked for other 2 models: 40000_G.pth and 40000_E.pth
However, 40000_optimizerG.pth is giving error.

**Comment by Viliars** [comment]
> Yes I am using latest code for SwinIR/main_test_swinir.py. It worked for other 2 models: 40000_G.pth and 40000_E.pth
> However, 40000_optimizerG.pth is giving error.

The word "optimizer" in "40000_optimizerG.pth" means that it is an optimizer, not a model.
"40000_G.pth" - is the latest model.
"40000_E.pth" - is the latest model using the EMA strategy.

The authors recommend using EMA - this model is more stable.

**Comment by JingyunLiang** [comment]
You only need the "40000_E.pth" (the EMA version of model) for testing. "40000_G.pth" stores the original version of model. "40000_optimizerG.pth" only stores the optimizer information, no model parameters.

**Comment by paragon1234** [comment]
Thank you. Can you provide details on what is 4000_E? How does GAN came into the picture?

**Comment by JingyunLiang** [comment]
EMA strategy can make GAN training more stable. You can find some insights [here](https://openreview.net/forum?id=SJgw_sRqFQ).
