### ISSUE TITLE
About ape

### ISSUE THREAD

**Issue by CHENBIN99** [JingyunLiang/SwinIR#31]
Thanks for your code first! 
After reading your code, I want to kown why don't use ape(absolute position embedding) in this code, because i saw the option is False by default.
I also want to confirm that if I use the 128-size pic to train the model with ape, could I can change the image size when I evaluation the model. I thought the length of position embedding is related to the num of patches, and the num of patches is related to the image size.
Hope you can solve my problem!

**Comment by JingyunLiang** [comment]
1) I didn't test ape because relative position embedding has shown better performance in other tasks.
2) Yes, you can. See more discussions in https://github.com/JingyunLiang/SwinIR/issues/9.

**Comment by CHENBIN99** [comment]
Thanks for your answer!
