### ISSUE TITLE
关于PSNR和SSIM没有收敛到原论文中的性能

### ISSUE THREAD

**Issue by lyongo** [JingyunLiang/SwinIR#34]
作者你好，

  谢谢你所做的非常不错的工作，我阅读了SwinIR论文，并且star了此仓库。在我使用你们提供的预训练模型在Set5数据集上测试 和在DIV2K和Flickr2K数据集训练Class Imager(x2)时，发现PSNR值没有达到原论文中的值，在这里请教下是否因为我的超参数设置的问题还是有些训练的trick。

  使用官方的预训练模型(001_classicalSR_DF2K_s64w8_SwinIR-M_x2.pth),在Set5上测试：
![image](https://user-images.githubusercontent.com/48617091/135701644-5429b06c-2fb7-4ce3-a86a-f97c1b8d906b.png)

  Average PSNR: 36.21 dB;  
  
  
  使用https://github.com/cszn/KAIR 中提供的训练代码 在DIV2K和Flickr2K数据集训练Class Imager(x2) 时：
![image](https://user-images.githubusercontent.com/48617091/135701807-9248edd6-28d9-4cf0-8d2d-06725eb79c18.png)

 Average PSNR 收敛到36.15dB，没达到论文中的性能。

谢谢！

**Comment by JingyunLiang** [comment]
1) We compare the Y-channel PSNR for image SR, the pretrained model achieves the same results as in Table 1 of the paper.

2) For your own training, do you use the same batch size and other settings? It is also possible that different runs may generate slightly different results (<0.06dB).

3) Lastly, could use the `mian_test_swinir.py` to test your trained model on other datasets? What are their PSNR?

**Comment by lyongo** [comment]
> 1. We compare the Y-channel PSNR for image SR, the pretrained model achieves the same results as in Table 1 of the paper.
> 2. For your own training, do you use the same batch size and other settings? It is also possible that different runs may generate slightly different results (<0.06dB).
> 3. Lastly, could use the `mian_test_swinir.py` to test your trained model on other datasets? What are their PSNR?

**Comment by lyongo** [comment]
> 1. We compare the Y-channel PSNR for image SR, the pretrained model achieves the same results as in Table 1 of the paper.
> 2. For your own training, do you use the same batch size and other settings? It is also possible that different runs may generate slightly different results (<0.06dB).
> 3. Lastly, could use the `mian_test_swinir.py` to test your trained model on other datasets? What are their PSNR?

谢谢您的回复 ，

1.  在SwinIR 论文的Table 2 中与SwinIR对比的Classical image SR 方法的PSNR的指标使用的都是 Y-channel PSNR 吗？

2.  如何使用自己训练的SwinIR模型在`mian_test_swinir.py`中测试呢？

**Comment by JingyunLiang** [comment]
1, Yes. We pointed it out in experimental setup.

2, Just use your own trained model path

**Comment by wfz666** [comment]
为什么我同样的代码和options，只能收敛到36.00左右？能告诉我你是什么option吗
