### ISSUE TITLE
Cuda out of memory for photos larger than 640x480px on RTX 3060 12GB

### ISSUE THREAD

**Issue by zelenooki87** [JingyunLiang/SwinIR#36]
Thanks for great code released for free to public. Tried real world 4x large model. Results are great. Even better than known commercial products. 
Real esrgan for example has --tile option for cuda out of memory errors. With your code I cant upscale larger than vga resolution photos with RTX 3060 12GB. Please tell me is there way for tiling or do I need to change img_size, for what values?
Thank you very much in advance!

**Comment by JingyunLiang** [comment]
Thanks for your advice. We have add an option `--tile` for testing it on large images. Example usages:
```
python main_test_swinir.py --task real_sr --scale 4 --model_path model_zoo/swinir/003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth --folder_lq testsets/RealSRSet+5images --tile 400
```
