### ISSUE TITLE
About test part in training

### ISSUE THREAD

**Issue by timerobin** [JingyunLiang/SwinIR#39]
Thanks for your code first!
I run the super-resolution lightweight part of the code, and there is an error in the testing part of training:

`Traceback (most recent call last):
  File "main_train_psnr.py", line 291, in <module>
    main()
  File "main_train_psnr.py", line 190, in main
    current_psnr = util.calculate_psnr(E_img, H_img, border=border)
  File "/home/ET/huiyuxiang/KAIR/utils/utils_image.py", line 632, in calculate_psnr
    raise ValueError('Input images must have the same dimensions.')
ValueError: Input images must have the same dimensions.`

So that I print the shape  and find it is padding the LR image to be multiple of 8  without HR image.

**Comment by Quentin-Anthony** [comment]
Looks like my issue is related to the google drive Set5 dataset: https://github.com/cszn/KAIR/issues/95#issuecomment-962533129

Using this repo's Set5 dataset works fine.
