### ISSUE TITLE
About the FLOPs of SwinIR

### ISSUE THREAD

**Issue by yueruchen** [JingyunLiang/SwinIR#41]
Hi,

Thanks for sharing the code of this interesting work. Would you mind helping provide the FLOPs cost of SwinIR? E.g., FLOPs under 256x256x3 images. Thanks!

**Comment by JingyunLiang** [comment]
Please refer to the code below
https://github.com/JingyunLiang/SwinIR/blob/510b75617620b05f4e35f74dec8d30d59c721cf6/models/network_swinir.py#L862

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.

**Comment by HeasonLee** [comment]
Hi, I have a problem with SwinIR's FLOPs. In SwinIR/models/network_swinir.py, line 849:
`flops += H * W * 3 * self.embed_dim * self.embed_dim`
 It doesn't look like a convolution calculation. Which operation does this row correspond to?
