### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by RebornForPower** [JingyunLiang/SwinIR#42]
Thanks for sharing your work. I meet a problem that the CPU usage is too high. When i set the H_size > 64  (eg.96 or 128) , the CPU usage is about 500%. I want to know why and what your type of GPU is used in the experiment in your paper. And I wonder if this problem is caused by the weak computing power of GPU (My GPU is NVIDIA RTX 2080 Ti).
Thanks~

**Comment by RebornForPower** [comment]
@JingyunLiang

**Comment by JingyunLiang** [comment]
Sorry for the later reply.

1, I think 500% CPU usage is normal. The upper bound is not 100%. If you want to reduce CPU usage, reduce the n_worker for the dataloader. 

2, I use RTX 2080Ti as well.

**Comment by RebornForPower** [comment]
Thanks for your replaying~
