### ISSUE TITLE
About training code

### ISSUE THREAD

**Issue by Freeman-Cai** [JingyunLiang/SwinIR#43]
I have download the training code from _https://github.com/cszn/KAIR_  but it generates the G and E models when i try to do a SR task. Do I download the wrong code?

**Comment by JingyunLiang** [comment]
No. It's correct. G and E means the commonly used Generator and the Generator_EMA (the interpolation between models of the last iteration and the current iteration. It leads to more stable model training.)

**Comment by Freeman-Cai** [comment]
Thanks for your reply! I will go on to understand the code.

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.

**Comment by kelvennn** [comment]
> No. It's correct. G and E means the commonly used Generator and the Generator_EMA (the interpolation between models of the last iteration and the current iteration. It leads to more stable model training.)

then what .pth fields should I load when I want to perform the test.py after training?
