### ISSUE TITLE
[SUGGESTION] Optimized version for videos

### ISSUE THREAD

**Issue by forart** [JingyunLiang/SwinIR#47]
Hi there, SwinIR is really cool !

Sice it has been "ported" to VapourSynth (thanks to @HolyWu) some interesting discussions - with tests too - about its effectiveness on videos started:
- http://forum.doom9.org/showthread.php?p=1956669#post1956669
- https://forum.videohelp.com/threads/399360-so-where-s-all-the-Topaz-Video-Enhance-AI-discussion/page13#post2634990

Seems that the main issue is the processing speed, btw someone argue that the algorithm is not (yet ?) optimized for videos...

About speed: @xinntao may help to implement an NCNN-Vulkan (as already done for [Real-ESGRAN](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan))...

About video optimizations: a collaboration with @ding3820 of [MIMO-VRN](https://github.com/ding3820/MIMO-VRN) project may help...

Hope that inspires.

**Comment by JingyunLiang** [comment]
Thank you for your advice. We will look at it after CVPR deadline.

**Comment by 4uma96** [comment]
I join the request, please make an NCNN-Vulkan implementation when the time appears.

**Comment by JingyunLiang** [comment]
See VRT(https://github.com/JingyunLiang/VRT) and RVRT (https://github.com/JingyunLiang/RVRT) for transformer-based video restoration (sr, deblurring, denoising, frame interpolation and space-time VSR)
