### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by sherlybe** [JingyunLiang/SwinIR#48]
hi,this is great work. I want to use this network for single image deraining, and what parts of this code can I modify? Or do you have any good suggestions? thanks!

**Comment by JingyunLiang** [comment]
SwinIR has not been tested on deraining yet, but it should be able to generalize to different restoration tasks.

**Comment by sherlybe** [comment]
> SwinIR has not been tested on deraining yet, but it should be able to generalize to different restoration tasks.

ok  谢谢

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions

**Comment by sherlybe** [comment]
hi,when i test denosing,shows the following error. how to slove it? thanks
![image](https://user-images.githubusercontent.com/82870143/143169783-87ca1a1b-aa73-4e0c-bd37-cd92ccbb77ff.png)

**Comment by JingyunLiang** [comment]
Incorrect image path.

**Comment by sherlybe** [comment]
> Incorrect image path.

![image](https://user-images.githubusercontent.com/82870143/143183599-27d417a6-9cf2-49ab-a0ae-deaeee4405cb.png)
i dont modify the path.

**Comment by sherlybe** [comment]
![image](https://user-images.githubusercontent.com/82870143/143184157-babd98d6-b3b1-48b7-adec-4c6b231256b6.png)
as the above...

**Comment by JingyunLiang** [comment]
It seems that you are using Windows. I guess the path may not be correct (Windows may use \\\\ instead of / for file path). Could you please add
```
print(path)
```
below this line?
https://github.com/JingyunLiang/SwinIR/blob/c24fb460d41e0d7e87b9c16854a4acdb01db5a82/main_test_swinir.py#L60

**Comment by sherlybe** [comment]
ok  it work,thanks! 
but i have a question,from the Visual comparison,SwinIR seems the image is more smooth, 这就是处理过后的效果吗？
![image](https://user-images.githubusercontent.com/82870143/143186288-c36aaec3-0475-48da-827b-0c8f1b0a42a2.png)
![6_SwinIR](https://user-images.githubusercontent.com/82870143/143186319-6eadbafc-5d53-429c-a845-c30e7b0e2136.png)

**Comment by sherlybe** [comment]
为了方便我还是用中文跟您交流吧。还有一个问题就是，您认为什么任务对于去雨的泛化效果最好？

**Comment by JingyunLiang** [comment]
For the first question, what are the compared methods? What is your setting?

For the second question, I think if you wanna test it on deraining, train it on deraining datasets.

**Comment by sherlybe** [comment]
> For the first question, what are the compared methods? What is your setting?
> 
> For the second question, I think if you wanna test it on deraining, train it on deraining datasets.

第一个问题我意思是如图所示，第一幅图是您的测试数据集McMaster里的图片，第二幅图是测试出的result图，我的问题是：结果图看起来比测试图像更平滑了，这就是本方法的复原效果吗？

**Comment by JingyunLiang** [comment]
Since SwinIR is only trained by L1 loss in this case, blurry results are expected. If you want to make it be sharp, you can add GAN loss and perceptual loss as in real-world image SR.

**Comment by sherlybe** [comment]
ok i got it！您的方法非常具有研究性，我会继续深入研究，后续一定会有很多问题值得和您讨论。非常感谢！

**Comment by sherlybe** [comment]
hi，经过几天的研究， 我带着问题回来了。根据您的建议，我重新对模型进行训练。我使用1200对图像进行训练，我的训练日志如下txt文件，我设置的dataset_type：dncnn，由于设备条件限制，我设置了numwork==0，batch_size==1,为了快速查看模型效果，我设置了100个epoch，一共训练九个小时，训练出结果显示，对于去雨并无效果（是我的训练设置出问题了吗？）我的trainH全是高清图像，trainL是加了雨纹的图像，如果我按照要求将图像成对的训练，我把dataset_type改成plain，但是它报错了，如下图所示，我该如何解决？
[trainlog.txt](https://github.com/JingyunLiang/SwinIR/files/7614960/trainlog.txt)
![image](https://user-images.githubusercontent.com/82870143/143797371-62ec9708-0cb0-4e91-b9be-f99867d3a88c.png)

**Comment by Zruto** [comment]
> hi，经过几天的研究， 我带着问题回来了。根据您的建议，我重新对模型进行训练。我使用1200对图像进行训练，我的训练日志如下txt文件，我设置的dataset_type：dncnn，由于设备条件限制，我设置了numwork==0，batch_size==1,为了快速查看模型效果，我设置了100个epoch，一共训练九个小时，训练出结果显示，对于去雨并无效果（是我的训练设置出问题了吗？）我的trainH全是高清图像，trainL是加了雨纹的图像，如果我按照要求将图像成对的训练，我把dataset_type改成plain，但是它报错了，如下图所示，我该如何解决？ [trainlog.txt](https://github.com/JingyunLiang/SwinIR/files/7614960/trainlog.txt) ![image](https://user-images.githubusercontent.com/82870143/143797371-62ec9708-0cb0-4e91-b9be-f99867d3a88c.png)

你好，可以交流一下关于去雨的训练代码吗
