### ISSUE TITLE
The input size during test

### ISSUE THREAD

**Issue by IceClear** [JingyunLiang/SwinIR#5]
Hi, Jingyun, nice work! I just wonder why SwinIR function needs to set the 'img_size'. It is somehow kind of inconvenient, especially for test, since we usually want to test on different sizes of images, right? Is there any particular reason for this? Since Swin Transformer does not need this because they use padding operations. Besides, are there any requirements of the input size, i.e., must be the multiple of a number, or something else? Thanks.

**Comment by z625715875** [comment]
Hi, @JingyunLiang 

Can I ask why we use the cropped like  $ 128 \times 128 \times 3 $ (so-called patch size) for training, instead of using the same size as used in the validation phase? 

Thank you.

**Comment by z625715875** [comment]
@JingyunLiang  Besides, the window size (namely the patch_size in your [network_swinir.py](https://github.com/JingyunLiang/SwinIR/blob/main/models/network_swinir.py#L680) ) for denoising is set to 1, what does that mean? Can I understand in this way:  actually there is no so-called window, instead, the denoising is based on pixel-wise attention?

**Comment by JingyunLiang** [comment]
- In training, you need to use the same image size for batch training. In validation, different testing images may have different sizes. The common practice is to randomly crop 64x64 or 128x128 image patches for training.
- Sorry for the abuse of notations.  **Just forget all notations/definition and I will give you a concrete example**. Given a 433x532 training image, we crop a 128x128 image patch for training. The 128x128 image is divided into non-overlapping 8x8 windows. In side each 8x8 window, we compute the attention matrix between every pixel (1x1).

**Comment by z625715875** [comment]
Thank you very much for the example. I totally understand your setting now. ^_^
