### ISSUE TITLE
Training efficiency

### ISSUE THREAD

**Issue by Linfeng-Tang** [JingyunLiang/SwinIR#53]
Hi

Thanks for the great work again.

When training SWIR with the KAIR toolbox, I found that the CPU utilization was particularly high, while the GPU was always idle. And the training is particularly inefficient. I wonder if the author would be so kind as to tell me the GPU and CPU configurations used, and the training time?

**Comment by JingyunLiang** [comment]
Do you use DstributedDataParallel (DDP)?

**Comment by Linfeng-Tang** [comment]
Actually, I did not use DstributedDataParallel (DDP).  And, I ran: "python main_train_psnr.py --opt options/swinir/train_swinir_sr_lightweight.json".

**Comment by JingyunLiang** [comment]
This is the reason. DDP is much quicker than DP.
