### ISSUE TITLE
Questions about the training effiency

### ISSUE THREAD

**Issue by XiaoqiangZhou** [JingyunLiang/SwinIR#57]
Thanks for releasing the code of SiwnIR, which is a really great work for low-level vision tasks.

However, when I train the SwinIR model with the guidance provided in the repo, I find the training efficiency is relatively low. 

Specifically, the GPU utilization rate keeps 0 for a while from time to time (run 14 seconds and sleep 14 seconds). When the GPU utilization rate is 0, the CPU utilization is also 0. It's worth noting that I use the DDP training on 8 TITAN-RTX GPU cards with the default batch_size. I train the classic SR task with DIV2K dataset on X2 scale. After half-day training, The epoch, iteration and PSNR on Set5 are about 1500, 42000 and 35.73dB, respectively. So, it will takes about 5 days to finish the 500k iterations, far exceeding the 2 days reported in the README.

Could you please help me to figure out the reason for training efficiency?

**Comment by JingyunLiang** [comment]
It's strange. When I use DDP, the GPU utilization fluctuates but is always high (70%-100%). Can you try to train the model using one GPU and check the GPU utilization?

**Comment by XiaoqiangZhou** [comment]
Thanks for your quick reply~

Following your instruction, I try to train the model using one GPU to verify the GPU utilization.
After changing the `gpu_ids` in the config file from `[0,1,2,3,4,5,6,7]` to `[0]` and changing to corresponding `dataloader_batch_size` from 32 to 4, I have tried two ways to train the model, i.e., DDP and DP, with one Titan-RTX GPU card.

When I use DP,  by running `python main_train_psnr.py --opt options/swinir/the_config_file.json`, the GPU utilization keeps around 50%. Maybe I can try to increase the batch_size to fully utilize the GPU capacity under DP mode?

When I use DDP, by running `python -m torch.distributed.launch --nproc_per_node=1 --master_port=1234 main_train_psnr.py --opt options/swinir/the_config_file.json  --dist True`, the low-efficiency phenomenon still exists. So the problem may be caused by the DDP training process. I think I may try to adjust some other configurations such as `dataloader_num_workers` if I insist on using DDP mode. Do you have any other suggestion?

I will try to solve this problem in the coming days and update my progress here. If there is no progress on the GPU utilization, I will close this issue.

Thanks.

**Comment by XiaoqiangZhou** [comment]
By the way, I'm using the `torch==1.7.0`.

**Comment by Priahi** [comment]
@XiaoqiangZhou any update on this? I am also facing similarly slow training time. With batch size 16 and 1000 iterations per epoch, it takes about 1000 seconds to run a single epoch, any insights on this @JingyunLiang?

**Comment by blackcow** [comment]
I have the same problem, GPU utilization is very low.

**Comment by Nodice** [comment]
I'm able to maintain close to 100% 4x GPU use on 4 RTX A6000 on Medium and Large RealSR models. Adjust your dataloader_num_workers to the max: 16, and set your dataloader_batch_size to the maximum your GPU's can hold. For the Medium model I was at 64 and for the large 32. The A6000's I have are 48gigs so a Titan RTX would be half.

Increasing the batch sizes slows down each iteration as its going through more images so take that into consideration. 

The CPU(s) is also a limitation on the Real World model and it's using degradation to generate the lr images. I had to upgrade my CPU to make sure it was not a bottle neck.

I'm Running 1.10.0+cu113

With that though, it's still taking a long time to train. I'm at 462k iterations after 5 days on a Large Model, roughly 3 minutes per 200 iterations.

**Comment by lucky-zwx** [comment]
各位解决这个问题了么？

**Comment by songwg188** [comment]
You can try to cut the large pictures in the training set into small pictures, because a lot of IO time is spent reading high-resolution images.

After using this method, the GPU utilization rate did not appear 0 during my training. If there are still problems, the CPU performance in the server is probably insufficient.

**Comment by JingyunLiang** [comment]
Thank you @songwg188

**Comment by Changlin-Lee** [comment]
I am facing the same issue. By following the suggestion, I use 224*224 as my training size, which I think is relatively small. When I try to train the model with DDP, the  GPU utilization keeps to 0% for a while.

**Comment by BeaverInGreenland** [comment]
> You can try to cut the large pictures in the training set into small pictures, because a lot of IO time is spent reading high-resolution images.

Should you do it for both High Res and Low Res images?
