### ISSUE TITLE
About clipping additive noise

### ISSUE THREAD

**Issue by yueruchen** [JingyunLiang/SwinIR#58]
Hi, thanks for sharing this work.

I have a question about AWGN denoising task. When building the noisy examples, do you clip the noisy images to [0, 255] or use unbounded images, on both training and testing?

Thanks

**Comment by JingyunLiang** [comment]
Unbounded. You can find the details in [KAIR](https://github.com/cszn/KAIR).

**Comment by yueruchen** [comment]
Thanks!
