### ISSUE TITLE
Ablation of the shallow feature extraction ?

### ISSUE THREAD

**Issue by Zeqiang-Lai** [JingyunLiang/SwinIR#59]
Have you perform an ablation study on the shallow feature extraction? 
How much PSNR gain can this module achieve?

**Comment by JingyunLiang** [comment]
No ablation study on it in the paper. I tried to replace a single convolution layer with the RRDB block/RCAN block, but they didn't help much.

**Comment by Zeqiang-Lai** [comment]
Did you try a model without this shall feature extraction module? i.e. Directly feed the image into transformer phase

**Comment by JingyunLiang** [comment]
You always need some layers to map the RGB channel (i.e., 3) to the feature channel (e.g., 180). Maybe you can try using a linear layer, but I have never tried it.
