### ISSUE TITLE
Looking forward to your training code

### ISSUE THREAD

**Issue by shikangouyang** [JingyunLiang/SwinIR#6]
Looking forward to your training code

**Comment by JingyunLiang** [comment]
Thanks for your issue. We have release [the SwinIR training code at KAIR](https://github.com/cszn/KAIR/blob/master/docs/README_SwinIR.md).  We also add an [interactive online Colab demo for real-world image SR](https://colab.research.google.com/gist/JingyunLiang/a5e3e54bc9ef8d7bf594f6fee8208533/swinir-demo-on-real-world-image-sr.ipynb).
