### ISSUE TITLE
about attn_mask and relative_position_bias

### ISSUE THREAD

**Issue by YangGangZhiQi** [JingyunLiang/SwinIR#61]
Hi, thank you very much for this Great work! 
    I read your code and paper several times. I can't understand attn_mask and relative_position_bias totally. 

![attn_mask疑问2](https://user-images.githubusercontent.com/87355944/146506473-cfa415ef-a1ca-4123-8777-a6c639cffd26.png)
In Line 134, why do we just add attn_mask to attn, not multiply?  In this way, attn_mask seems like a bias, like relative_popsition_bias in Line 130.  
I would appriciate it if someone could help me.

**Comment by JingyunLiang** [comment]
This is because we add the attn_mask (with -100 or 0) before softmax function.  ``A^(x-100) = A^x * A^(-100) = A^x * 0 = 0``

**Comment by YangGangZhiQi** [comment]
@JingyunLiang  Thanks for your so quick reply.  I get it.  
About  relative_position_bias, how to understand it?  what's the role of relative_position_bias in WindowAttention module? It seems like atten = q @ k + relative_position_bias, what would happen if we do not use relative_position_bias? 
I am beginner in SwinIR, Sorry for such questions may take your time.

**Comment by JingyunLiang** [comment]
`relative_position_bias` can tell you the relative position of two pixels. A pixel should have higher impact on its neighbhouring pixels than distanct pixels.

**Comment by YangGangZhiQi** [comment]
I get it. Thanks again!
