### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by YangGangZhiQi** [JingyunLiang/SwinIR#62]
Hi，thanks for such great work!
      I am reproducing your swinIR results in realSR task. When using realSR-SwinIR-L config to train realSR model, a bug came out as below. But when using realSR-SwinIR-S config, no bug at all.
<img width="749" alt="swinIR_RealSRL" src="https://user-images.githubusercontent.com/87355944/147399362-e26e1584-3cf6-4904-9636-364fee5e5dc5.png">
     I guess the bug comes from resi_connection='3conv'，only this place will produce kernel shape [60,60,1,1]. This really troubles me that the code seems like right. Why it comes out this bug. I would appreciate it if anyone could help me.
<img width="569" alt="bug" src="https://user-images.githubusercontent.com/87355944/147399426-c7c77dea-f1ce-4ddc-8547-027152bedb62.png">
I use DDP when training realSR model.
System config:
Ubuntu 16.04
cuda 11.1
pytorch 1.8

**Comment by JingyunLiang** [comment]
If it's just waring, it doesn't matter.
