### ISSUE TITLE
Colab Notebook is NOT Opening

### ISSUE THREAD

**Issue by Adeel-Intizar** [JingyunLiang/SwinIR#63]
Hi, 
Thank you for your amazing work, the colab notebook link provided in this repo is not opening, can you upload the notebook in this repo or fix the notebook url ?

Thank you

**Comment by JingyunLiang** [comment]
It works well for me. You may need a VPN because it's a service from Google.

**Comment by Adeel-Intizar** [comment]
it keeps on loading just as before but never opens even after using the VPN

**Comment by Adeel-Intizar** [comment]
it'll be helpful if you can upload that notebook in this repo

**Comment by JingyunLiang** [comment]
There is no meaning to do so. It uses the GPU from Google (Colab) in the demo. You cannot use it without a Google GPU. It's not a jupyter notework.
