### ISSUE TITLE
Training Issues

### ISSUE THREAD

**Issue by msx-123** [JingyunLiang/SwinIR#64]
First of all, thank you for your excellent work.
Currently I have two questions.
1. The training demo you gave has the training in the main_train_psnr.py file, but I don't find this main_train_psnr file in the project, how do I train it?
2. I am more concerned about the training configuration and training time, how long did you train the DIV2K dataset with classic super resolution using what configuration of graphics card?
Looking forward to your reply, thanks!

**Comment by JingyunLiang** [comment]
1, See https://github.com/cszn/KAIR/blob/master/docs/README_SwinIR.md

2, See https://github.com/JingyunLiang/SwinIR/blob/main/README.md

**Comment by JingyunLiang** [comment]
If you meet I/O bottleneck, preparing the dataset as lmdb (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/create_lmdb.py) or extracting them as small patches (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/extract_subimages.py) can help a lot. The PSNR performance will the same.

**Comment by jiamingNo1** [comment]
> If you meet I/O bottleneck, preparing the dataset as lmdb (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/create_lmdb.py) or extracting them as small patches (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/extract_subimages.py) can help a lot. The PSNR performance will the same.

how to use the lmdb file?
