### ISSUE TITLE
where can I find your datasets (DIV2K bicubic x8)?

### ISSUE THREAD

**Issue by HWalkingMan** [JingyunLiang/SwinIR#71]
I see SwinIR can also handle the classical image SR with **x8** scaling factor. Where can I find your datasets(DIV2K bicubic x8)？

**Comment by Nodice** [comment]
@HWalkingMan He lists all of the datasets and gives links to them in the main readme. DIV2k here: https://cv.snu.ac.kr/research/EDSR/DIV2K.tar

I setup my own routines to build the training set, but as I recall there are python or matlab scripts over at his main framework project which is here: https://github.com/cszn/KAIR

It wasn't super clear as to what resolutions and settings he used, so maybe @JingyunLiang could chime in on this. The JSON files have 256 for the 4x medium model patch sizes and 64 lq. I would probably use 512 and 64 for an 8x.

**Comment by HWalkingMan** [comment]
Thanks for your help!

I notice that the dataset [DIV2K](https://cv.snu.ac.kr/research/EDSR/DIV2K.tar) contains only x4 scaling factor but no x8 scaling factor. 

Should I use my own script for downsampling?

**Comment by Nodice** [comment]
@HWalkingMan Yes, but you can use this to get you started. It's referenced in KAIR. 

https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md

and the script

https://github.com/xinntao/BasicSR/blob/master/scripts/data_preparation/extract_subimages.py

**Comment by JingyunLiang** [comment]
Thanks for your answer~ @Nodice
