### ISSUE TITLE
how to use .nii (MRI) files to super resolve my datatset using pre trained models

### ISSUE THREAD

**Issue by ixy40** [JingyunLiang/SwinIR#72]
hi 
I want to provide the input as a .nii file, i then convert it into the numpy .array format and i want to use the pretrained model 003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth .

how should i proceed and is it even valid to use these ore-trained models for .nii files specifically?

Thank you

**Comment by JingyunLiang** [comment]
We have discussed it via email.
