### ISSUE TITLE
Request about scale factor in Real-World SR

### ISSUE THREAD

**Issue by KazuCook** [JingyunLiang/SwinIR#73]
Thanks for your great work!
Is is possible to publish a checkpoint of scale-factor 2 (x2) in Real-World SR?

**Comment by orilifs** [comment]
Yea, for me aswell

**Comment by JingyunLiang** [comment]
X2 model is available at https://github.com/JingyunLiang/SwinIR/releases.

**Comment by orilifs** [comment]
Thank you

**Comment by dreamflasher** [comment]
@JingyunLiang Thank you, could you also please release the Large model for 2x? Large has a lot better quality.
