### ISSUE TITLE
计算时长问题

### ISSUE THREAD

**Issue by lucky-zwx** [JingyunLiang/SwinIR#76]
在实际运行时出现GPU间断工作问题，而且计算速度非常慢，是不是CPU瓶颈？
```
22-03-02 21:23:15.601 : <epoch:  7, iter:     200, lr:1.000e-04> G_loss: 9.836e-02 
22-03-02 21:30:06.462 : <epoch: 14, iter:     400, lr:1.000e-04> G_loss: 7.852e-02 
22-03-02 21:36:58.484 : <epoch: 21, iter:     600, lr:1.000e-04> G_loss: 8.976e-02 
```
处理器	英特尔 Xeon(至强) Silver 4210R @ 2.40GHz

主板	超微 X11DPG-QT

内存	128 GB ( 三星 3200MHz )

主硬盘	三星 MZ7LH960HAJR-00005 ( 960 GB / 固态硬盘 )

主显卡	Nvidia GeForce RTX 3090 ( 24 GB / 七彩虹 ) X 2 #81

**Comment by JingyunLiang** [comment]
If you meet I/O bottleneck, preparing the dataset as lmdb (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/create_lmdb.py) or extracting them as small patches (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/extract_subimages.py) can help a lot. The PSNR performance will the same.

**Comment by angleboy8** [comment]
> 在实际运行时出现GPU间断工作问题，而且计算速度非常慢，是不是CPU瓶颈？
> 
> ```
> 22-03-02 21:23:15.601 : <epoch:  7, iter:     200, lr:1.000e-04> G_loss: 9.836e-02 
> 22-03-02 21:30:06.462 : <epoch: 14, iter:     400, lr:1.000e-04> G_loss: 7.852e-02 
> 22-03-02 21:36:58.484 : <epoch: 21, iter:     600, lr:1.000e-04> G_loss: 8.976e-02 
> ```
> 
> 处理器	英特尔 Xeon(至强) Silver 4210R @ 2.40GHz
> 
> 主板	超微 X11DPG-QT
> 
> 内存	128 GB ( 三星 3200MHz )
> 
> 主硬盘	三星 MZ7LH960HAJR-00005 ( 960 GB / 固态硬盘 )
> 
> 主显卡	Nvidia GeForce RTX 3090 ( 24 GB / 七彩虹 ) X 2 #81

请问您根据作者提供的两种方法，解决了“训练速度慢“”这个问题没有？请问您如何解决的。在此，非常感谢您的帮助！
