### ISSUE TITLE
The paging file is too small for this operation to complete.

### ISSUE THREAD

**Issue by YildizzEmrah** [JingyunLiang/SwinIR#78]
Hello, I got this error so ı dont understand why this error comes to me. 

OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "D:\Anaconda\envs\swin-train\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

This is my option settings.
and ı run with console this line 

python main_train_psnr.py --opt options/swinir/train_swinir_sr_classical.json

![Adsız](https://user-images.githubusercontent.com/90452717/159191740-4edaa02e-d927-47e0-9057-2622419ce646.jpg)
I got 2 gpu , 1080ti gpu 0 and gpu 1 .

Please somene one can help me ? I want to train my own dataset whit swinir

**Comment by lucky-zwx** [comment]
num_works设置的太高了

**Comment by JingyunLiang** [comment]
@lucky-zwx Thank you for your answer.
