### ISSUE TITLE
Error in module 4

### ISSUE THREAD

**Issue by tavisc** [JingyunLiang/SwinIR#80]
I'm trying to upscale a single image before I run a batch, but I'm getting the following error in module 4: 

error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

I have no idea what this means or how to fix it.

**Comment by Haris-Ali007** [comment]
Check your path if you are reading image. This usually occurs, when image you are trying to pass is empty.

**Comment by JingyunLiang** [comment]
@Haris-Ali007 Thank you for your answer.
