### ISSUE TITLE
Training Speed of Swinir

### ISSUE THREAD

**Issue by caopulan** [JingyunLiang/SwinIR#81]
You mentioned the training time in this issues https://github.com/JingyunLiang/SwinIR/issues/3#issuecomment-905527703.
But it is much slower in my case.
I have tested it on two different machines, both of them are slower than yours, could you give me some suggestions, thanks!

options:https://github.com/cszn/KAIR/blob/master/options/swinir/train_swinir_sr_classical.json

Machine A:
8 * V100S-32G + CUDA 11.5 / CUDA11.2
200 iterations cost 175 seconds, which means the total training process (500k iterations) will cost 121 hours (5 days)

Machine B:
4 * 3090 + CUDA11.1
In this case, I set batch-size to 16.
200 iterations cost 85 seconds, the whole training will cost 60 hours (2.5 days)

These two results of training speed are much different from your experiment.

I have tried:
1. set find_unused_parameters to False
2. add amp
3. increase dataloader worker nums or set it to 0

But all of them didn't work. I have no idea to solve it, could you please help me, thank you.

**Comment by JingyunLiang** [comment]
If you meet I/O bottleneck, preparing the dataset as lmdb (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/create_lmdb.py) or extracting them as small patches (https://github.com/cszn/KAIR/blob/master/scripts/data_preparation/extract_subimages.py) can help a lot. The PSNR performance will the same.
