### ISSUE TITLE
About #Params and #Mult-Adds

### ISSUE THREAD

**Issue by junseokoh1** [JingyunLiang/SwinIR#87]
I'm try to calculate #params and #mult-adds with lightweight image SR model.
But my result is different from Table3.
I used thop libray (https://github.com/Lyken17/pytorch-OpCounter) and ptflops(https://github.com/sovrasov/flops-counter.pytorch/blob/7fe7d260bbdde12525c9bf109599683f5313a9a1/ptflops/flops_counter.py) library.
Can you tell me which libray did this paper used to calucualte #params and # mult-adds?

**Comment by ChamingHong** [comment]
> I'm try to calculate #params and #mult-adds with lightweight image SR model. But my result is different from Table3. I used thop libray (https://github.com/Lyken17/pytorch-OpCounter) and ptflops(https://github.com/sovrasov/flops-counter.pytorch/blob/7fe7d260bbdde12525c9bf109599683f5313a9a1/ptflops/flops_counter.py) library. Can you tell me which libray did this paper used to calucualte #params and # mult-adds?

hello, have you found a method to calculate #params and #mult-adds? I used the thop library but couldn't get the results in the paper. I'm very sorry if it bothers you.
