### ISSUE TITLE
About overlap strategy

### ISSUE THREAD

**Issue by junseokoh1** [JingyunLiang/SwinIR#91]
Thanks for your awesome work and release code.
I have some question about tile_overlap in main_test_swinir.py code.
Overlap tile strategy is purposed by U-Net paper and a widely-used trick in the field of super-resolution. For CNN based model, the super-resolution model up-scales the subregion image, including theri overlapping area, and the overlapping area in the output subregion is cut off.
I think overlap tile strategy used in main_test_swinir.py is little different from CNN based model.
I wonder if there is no tiling artifact in the method used here. And is there overlap tile strategy for swin transformer based model?
I would be very grateful if you could give me an answer.

**Comment by JingyunLiang** [comment]
If you have enough memory, you can directly test it by inputting the whole image, without any border artifacts. However, if you test the model by tile strategy, there are some border artifacts. If you have a better tile strategy that can alleviate the artifacts, feel free to pull a request.
