### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by gunerhui** [JingyunLiang/SwinIR#92]
It's too slow.I test image(600X600  scale 2),10s per image on gpu,it's too slow using realx2 model.
Is the speed normal?

**Comment by JingyunLiang** [comment]
It's not normal. As said in https://github.com/JingyunLiang/SwinIR#results, testing on a 256x256 LR image takes about 0.5s on a 2080Ti GPU.

**Comment by dsxailab** [comment]
It works fine on A4500 (> 1it/s), but it's slow on Nvidia A5000 and A6000 with 3s/it and sometimes even 30+s per it.
