### ISSUE TITLE
Replacement model problem

### ISSUE THREAD

**Issue by labels168** [JingyunLiang/SwinIR#97]
I use the following model and it executes fine
python main_test_swinir.py --task real_sr --scale 4 --model_path model_zoo/swinir/003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth --folder_lq testsets/RealSRSet+5images --tile

But if I change the model, there will be an error, I don't know how to fix this problem, please help, thanks!
python main_test_swinir.py --task real_sr --scale 4 --model_path model_zoo/swinir/003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x2_GAN.pth --folder_lq testsets/RealSRSet+5images --tile

The difference is in the model:
003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x2_GAN.pth

**Comment by jjdbear** [comment]
> 
I think 003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x2_GAN.pth is for scale 2, you can try change this parameter --scale 2

**Comment by JingyunLiang** [comment]
Thank you @jjdbear
