### ISSUE TITLE
An Inquiry about Patch Embedding

### ISSUE THREAD

**Issue by Huqy518** [JingyunLiang/SwinIR#99]
Dear authors,

Thanks for your great work! I have a question about the 'Patch Embed' class. It seems that there is no projection operation on the input image data. Maybe I am wrong, I think this code cannot work when we want to add the positional encodings without the projection operation.

I would appreciate too much if you could kindly help me.

Best Regards,
Qy

**Comment by JingyunLiang** [comment]
Yes, there is no projection. The positional encodings are added at https://github.com/JingyunLiang/SwinIR/blob/9b1a9bf5d1df3b18c32a49ea82f60c313d779f7d/models/network_swinir.py#L130
